### ISSUE TITLE
Errors when confirming to Identifier protocol.

### ISSUE THREAD

**Issue by ItzNotABug** [Teknasyon-Teknoloji/PersistenceKit#16]
<img width="844" alt="Screen Shot 2020-05-09 at 8 57 41 PM" src="https://user-images.githubusercontent.com/20625965/81477928-e8835880-9237-11ea-80d3-4242c14373fe.png">

**Comment by buraksyalcin** [comment]
You need to declare your id property as variable property.

```swift
var tex: String
```

**Comment by omaralbeik** [comment]
Nice catch @ItzNotABug!. For now, this is not possible with `let` as @buraksyalcin is suggesting.

---

## More to this issue
The source of the problem is that the [`Identifiable`](https://github.com/Teknasyon-Teknoloji/PersistenceKit/blob/master/Sources/Identifiable.swift) protocol requires a `WritableKeyPath`, which can not be used with constants by default.

But I don't see any reason why we should stick to it, it would be nice to release an update making it a normal `KeyPath`

```swift
public protocol Identifiable {
    associatedtype ID: Hashable
    static var idKey: KeyPath<Self, ID> { get }
}
```

and then it can be used with both `let` and `var` properties

```swift
struct TexStruct: Codable, Identifiable {
    static let idKey: KeyPath<TexStruct, String> = \.tex
    let/var tex: String
    ...
}
```

> This is a breaking change, so it is up to @buraksyalcin and his team to decide to release an update or keep the current behavior for compatibility reasons
